name: Build with cargo

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: target/**
          key: cargo
      - name: Install rust toolchain
        run: rustup update stable && rustup default stable && rustup target add x86_64-unknown-linux-musl
      - name: Build with cargo
        run: cargo build --verbose --release --target x86_64-unknown-linux-musl
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: loudness-server
          path: target/release/loudness-server
